apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-mongodb-pvc
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
