apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-chatapp-deployment
  namespace: chat-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: dp04/chatapp-frontend:latest

        ports:
        - containerPort: 80

        env:
        - name: NODE_ENV
          value: "production"

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 20
